name: TypeScript Action
author: Austen Stone
description: A TypeScript Action
branding:
  icon: "plus"
  color: "blue"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  all-secrets:
    description: A JSON string of all secrets
    default: ${{ toJson(secrets) }}
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
