name: TypeScript Action
author: Austen Stone
description: A TypeScript Action
branding:
  icon: "plus"
  color: "blue"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  owner:
    description: 'Optional repository owner to run the workflow on.'
    default: ${{ github.repository_owner }}
    required: false
  repo:
    description: 'Optional repository name to run the workflow on.'
    default: ${{ github.repository }}
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
